/** ====================================================================== **/
export const GET_CATEGORIES_PENDING = 'CATEGORIES/GET_CATEGORIES_PENDING';
export const GET_CATEGORIES_SUCCESS = 'CATEGORIES/GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_REJECTED = 'CATEGORIES/GET_CATEGORIES_REJECTED';
/** ====================================================================== **/
export const GET_CATEGORY_CONTENT_PENDING =
  'CATEGORIES/GET_CATEGORY_CONTENT_PENDING';
export const GET_CATEGORY_CONTENT_SUCCESS =
  'CATEGORIES/GET_CATEGORY_CONTENT_SUCCESS';
export const GET_CATEGORY_CONTENT_REJECTED =
  'CATEGORIES/GET_CATEGORY_CONTENT_REJECTED';
export const CATEGORIES_CLEAR = 'CATEGORIES/CATEGORIES_CLEAR';
